### ISSUE TITLE
txtconfig file not working

### ISSUE THREAD

**Issue by mandai2** [TopazTK/PCSX2-EX#14]
Hi I am trying to test with some texture replacements but it doesn't seem to be working.
Enable Manuplation Functions is ticked, set to Replace Textures.
Then I get the log message The config file for this game cannot be found or is invalid. Texture replacements are disabled.

I have a texture file PCSX2-EX\textures\mytextures\51180F90.dds

Then I created this file PCSX2-EX\txtconfig\5B86BB62.yaml
ProcessTEX: 
  0x51180F90: "mytextures/51180F90.dds"

This is with version 3.10.0 Base 1.6.0, game CRC is 5B86BB62. I am running Windows 10 64-bit

**Comment by duongvinhthai00** [comment]
me too

**Comment by duongvinhthai00** [comment]
I think it doesn't work anymore

**Comment by MadsPatter** [comment]
I cannot get it to read the file right, but it seems it uses the INI extension and not one with a YAML extension. This may just be the may version being behind current code.

**Comment by mandai2** [comment]
I figured out the .ini format. It should look like this example:
[ProcessSTD]
3074CD40=mytextures\3074CD40.dds

[ProcessSPC]
